# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SetForthMeshID
                                 A QGIS plugin
 SetForthMeshID to the field
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-10-06
        copyright            : (C) 2021 by Yoichi Kayama/Aeroasahi corporation
        email                : yoichi.kayama@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
from qgis.core import QgsMapLayerProxyModel

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SetForthMeshID class from file SetForthMeshID.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .SetForthMeshID import SetForthMeshID
    return SetForthMeshID(iface)
